### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by lucenzhong** [kamigaito/rnnlm-pytorch#1]
Hello，I run the code and got Error `RuntimeError: Given input size: (50x1x28). Calculated output size: (50x1x0). Output size is too small`. And I think it may be a problem with torch and torchvision version. Could you please tell me what torch and torchvision version do you use in this project? Thanks.

**Comment by Xuwanjun9** [comment]
> 
> 
> Hello，I run the code and got Error `RuntimeError: Given input size: (50x1x28). Calculated output size: (50x1x0). Output size is too small`. And I think it may be a problem with torch and torchvision version. Could you please tell me what torch and torchvision version do you use in this project? Thanks.

Hello， I got the same problem, have you solved this?

**Comment by Fly-ShuAI** [comment]
```
models.py
class CNNCharEmb(nn.Module):
def forward(self, input):
```

```
list_pooled.append(F.max_pool1d(conved,kernel_size=conved.shape[1]).squeeze(2))
```
change to: 
```
kernel_size = min(conved.shape[1], conved.shape[2]) 
list_pooled.append(F.max_pool1d(conved, kernel_size=kernel_size).squeeze(2))
```
